// Curated daily topics. The daily pick indexes this array by day-of-year
// (local date — see app.js). Add topics freely; order only affects which
// day a topic lands on.
window.TOPICS = [
  'Why you are made of star-stuff',
  'Why milk is a sneaky colloid squad',
  'How bees tell each other where the flowers are',
  'Why the sky is blue but sunsets are orange',
  'How your bones fix themselves when they break',
  'Why cats always land on their feet',
  'How a tiny seed knows which way is up',
  'Why the Moon changes shape every night',
  'How octopuses taste things with their arms',
  'Why popcorn pops',
  'How mountains grow taller very, very slowly',
  'Why your tummy rumbles when you are hungry',
  'How chameleons change colour',
  'Why ice floats instead of sinking',
  'How birds find their way home across the whole world',
  'Why onions make you cry',
  'How your heart never gets tired of beating',
  'Why thunder comes after lightning',
  'How ants carry things much heavier than themselves',
  'Why bananas are berries but strawberries are not',
  'How glow-worms make their own light',
  'Why you get goosebumps',
  'How aeroplanes stay up in the sky',
  'Why the ocean is salty',
  'How your brain keeps working while you sleep',
  'Why leaves change colour in autumn',
  'How dolphins see with sound',
  'Why volcanoes erupt',
  'How rainbows are made',
  'Why your fingers go wrinkly in the bath',
  'How spiders build webs without getting stuck',
  'Why the Earth spins but we never feel dizzy',
  'How penguins keep their feet from freezing',
  'Why bread rises before it is baked',
  'How electric eels make electricity',
  'Why we have two eyes instead of one',
  'How trees talk to each other underground',
  'Why the tide comes in and goes out',
  'How hummingbirds hover like tiny helicopters',
  'Why some things bounce and some things smash',
  'How your body turns food into energy',
  'Why deserts are hot in the day and cold at night',
  'How snakes smell with their tongues',
  'Why soap makes bubbles',
  'How earthquakes happen',
  'Why flamingos are pink',
  'How your voice comes out of your mouth',
  'Why magnets stick to some things and not others',
  'How caterpillars turn into butterflies',
  'Why yawning is contagious',
  'How sharks grow thousands of teeth',
  'Why the stars twinkle',
  'How honey never goes bad',
  'Why your shadow follows you around',
  'How fish breathe underwater',
  'Why hot air balloons float',
  'How your cuts and scrapes heal themselves',
  'Why zebras have stripes',
  'How echoes work',
  'Why we need to sleep every night',
  'How clouds hold all that rain without falling',
  'Why crocodiles cry real tears',
  'How your ears help you balance',
  'Why space is completely silent',
  'How fireflies flash messages to each other',
  'Why bubbles are always round',
  'How woodpeckers avoid headaches',
  'Why the sea sounds like the sea inside a shell',
  'How plants drink water through their roots',
  'Why some animals sleep all winter long',
];
